name: Build Architecture-Specific APKs

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.12.0
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-split-apks:
    name: Build Split APKs
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build architecture-specific APKs
      run: |
        echo "Building split APKs for all architectures..."
        flutter build apk --release --split-per-abi
    
    - name: Analyze APK sizes
      run: |
        echo "## 📊 APK Size Analysis" >> $GITHUB_STEP_SUMMARY
        echo "| APK File | Size | Architecture | Target Devices |" >> $GITHUB_STEP_SUMMARY
        echo "|----------|------|--------------|----------------|" >> $GITHUB_STEP_SUMMARY
        
        cd build/app/outputs/flutter-apk
        for apk in app-*.apk; do
          if [ -f "$apk" ]; then
            size=$(du -h "$apk" | cut -f1)
            arch=$(echo "$apk" | sed 's/app-\(.*\)-release\.apk/\1/')
            
            case $arch in
              "arm64-v8a")
                desc="ARM 64-bit | Modern Android phones (2019+)"
                ;;
              "armeabi-v7a")
                desc="ARM 32-bit | Older Android phones (2012-2019)"
                ;;
              "x86")
                desc="Intel 32-bit | Emulators/Intel tablets"
                ;;
              "x86_64")
                desc="Intel 64-bit | Emulators/Intel devices"
                ;;
              "universal")
                desc="Universal | All architectures (fallback)"
                ;;
              *)
                desc="Unknown | Unknown architecture"
                ;;
            esac
            
            echo "| $apk | $size | $desc |" >> $GITHUB_STEP_SUMMARY
          fi
        done
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🎯 Recommended Distribution" >> $GITHUB_STEP_SUMMARY
        echo "- **arm64-v8a**: Primary - Upload to Play Store for most users" >> $GITHUB_STEP_SUMMARY
        echo "- **armeabi-v7a**: Secondary - For older device support" >> $GITHUB_STEP_SUMMARY
        echo "- **universal**: Fallback - Keep as backup APK" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "💡 **Size Reduction**: Each split APK is ~75% smaller than universal!" >> $GITHUB_STEP_SUMMARY
    
    - name: Upload ARM64 APK
      uses: actions/upload-artifact@v4
      with:
        name: harmony-music-arm64-v8a
        path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
        
    - name: Upload ARM32 APK
      uses: actions/upload-artifact@v4
      with:
        name: harmony-music-armeabi-v7a
        path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
        
    - name: Upload x86_64 APK
      uses: actions/upload-artifact@v4
      with:
        name: harmony-music-x86_64
        path: build/app/outputs/flutter-apk/app-x86_64-release.apk
        
    - name: Upload x86 APK
      uses: actions/upload-artifact@v4
      with:
        name: harmony-music-x86
        path: build/app/outputs/flutter-apk/app-x86-release.apk
        
    - name: Upload Universal APK
      uses: actions/upload-artifact@v4
      with:
        name: harmony-music-universal
        path: build/app/outputs/flutter-apk/app-universal-release.apk
    
    # Create GitHub Release with all APKs
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          build/app/outputs/flutter-apk/app-x86_64-release.apk
          build/app/outputs/flutter-apk/app-x86-release.apk
          build/app/outputs/flutter-apk/app-universal-release.apk
        body: |
          ## 🏗️ Architecture-Specific APKs
          
          This release includes optimized APKs for different device architectures:
          
          ### 📱 Recommended Downloads
          - **app-arm64-v8a-release.apk**: For modern Android devices (2019+) - **Most users should download this**
          - **app-armeabi-v7a-release.apk**: For older Android devices (2012-2019)
          - **app-universal-release.apk**: Universal fallback (largest size)
          
          ### 🧪 Testing APKs
          - **app-x86_64-release.apk**: For Intel-based devices/emulators
          - **app-x86-release.apk**: For 32-bit Intel devices/emulators
          
          ### 💡 Size Benefits
          Each architecture-specific APK is ~75% smaller than the universal APK!
          
          ### 🔍 How to Choose
          Not sure which APK to download? Try **app-arm64-v8a-release.apk** first - it works on most modern Android devices.
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}